Enable strict mode in tsconfig.json
sanity-io/structured-content-2022 pull request #168
Opened 2022-05-03 11:25 UTC by j0nas

# Enable strict mode in tsconfig.json

## Intent

Enable TypeScript _strict mode_ for _/web_.

Solves the underlying issue of [this Shortcut Story](https://app.shortcut.com/sanity-io/story/19097/urgent-site-not-refreshing).

## Description

The `strict` setting in _tsconfig.json_ was set to `false`, which opts us out of a lot of the benefits that one comes to expect of a compiled, type-safe language. Unfortunately, I didn't discover this until quite recently, when the linked Shortcut Story was reported. This PR enables this setting for the _web_ directory, and does the bare minimum necessary to have CI passing again with the new checks in place. [As noted on Slack](https://wja.slack.com/archives/C02AX66E2S0/p1651479109756419), having this flag set to `true` would likely have prevented the build error encountered in the linked Story.

This PR touches many files, but you will quickly discover that most of the fixes are fairly similar in nature. My approach to enable the `strict` flag was to fix the reported issues one-by-one until there were none left. This may have led to some types of fixes being applied in a slightly inconsistent way. This was a result of the sheer number of errors initially reported, and the fact that I didn't discover that I could report _all_ errors using `npx tsc --noEmit` (instead of one-by-one as was the output of `yarn build`) until quite late into the fixing process. (I had to stop myself several times from performing larger-scale refactorings; such things should definitely be done in follow-up issues & PRs.) Sorry if this PR feels a bit chaotic. Please feel free to suggest fixes for any such inconsistencies if you find any, or (preferably) file issues that are to be followed up in later PRs.

## Testing this PR

Verify that the [Preview Deploy for this PR](https://structured-content-2022-web-git-tsconfig-strict-mode.sanity.build/) renders identically to other Preview Deploys using the `staging` dataset (e.g. the [Preview Deploy](https://structured-content-2022-web-git-generate-og-image.sanity.build/) for #167). Expecting to go through every single page is not realistic, but focus on the most important parts, for instance the front page and the Program page.

2022-05-04 18:44 UTC, oyvind-stenhaug requested changes
Great work, I'm glad TS can be made to catch a few more issues than it previously has.

Added some issues and comments inline, though most of them are labelled as nit. Might be worth noting that GitHub hides some of it behind a "Load more" button.

2022-05-05 09:36 UTC, j0nas commented on web/components/SessionSpeakers/SessionSpeakers.tsx
> +    <div className={styles.column2} aria-hidden={Boolean(speaker2)}>
dd7761b.

2022-05-05 09:37 UTC, j0nas commented on web/components/Nav/MenuItem/MenuItem.tsx
> +      {href ? <Link href={href}>{Anchor}</Link> : Anchor}
82ceee9.

2022-05-05 09:59 UTC, j0nas commented on web/components/TextBlock/SponsorsSection/SponsorsSection.tsx
> +                  {sponsors?.map((sponsor) => (
Yeah. Predicates are a bit clumsy to define when dealing with complex/nested types, so I figured that the optional chaining was a simpler way to go about it to appease TS.

2022-05-05 10:00 UTC, j0nas commented on web/components/TextBlock/Programs/Programs.tsx
> +                    person?.photo &&
7bb71f2

2022-05-05 10:00 UTC, j0nas commented on web/components/TextBlock/Programs/Programs.tsx
> +                  session.session!._id,
95295a7

2022-05-05 10:01 UTC, j0nas commented on web/components/TextBlock/Programs/Programs.tsx
> +                  Section
51acbc4.

2022-05-05 10:17 UTC, j0nas commented on web/components/TextBlock/Sponsorships/Sponsorships.tsx
> +                  name={b || ''}
4b8a2b9? Feels slightly more idiomatic.

2022-05-05 10:42 UTC, j0nas commented on web/components/VenueNav/VenueNav.tsx
> +      [mainVenue?.name || '']: 'Main venue',
d879c53

2022-05-05 10:44 UTC, j0nas commented on web/pages/[[...slug]].tsx
>      : slugParam || '/';
Yeah, looking at this with fresh eyes, I can immediately tell this doesn't look right. In 3df84d3, I copied over a `getSlug` util function which I initially wrote for the [Venue Details](https://github.com/sanity-io/structured-content-2022/compare/venue-details) branch. which saves us duplicating these possibly confusing snippets. What do you think?

2022-05-05 10:46 UTC, j0nas commented
@oyvind-stenhaug Thank you for the thorough review. :100:

2022-05-05 11:50 UTC, oyvind-stenhaug commented on web/components/SessionSpeakers/SessionSpeakers.tsx
> +    <div className={styles.column2} aria-hidden={!Boolean(speaker2)}>
Hm, I was about to write that this is probably fine. But now I see this note: https://w3c.github.io/aria/#h-note-53

> At the time of this writing, `aria-hidden="false"` is known to work inconsistently in browsers. As future implementations improve, use caution and test thoroughly before relying on this approach.

So I would really prefer to keep the original behavior of not outputting the attribute at all when the speaker is absent. As far as I can tell, TS is appeased by replacing the original `null` with `undefined`:

```suggestion
    <div className={styles.column2} aria-hidden={speaker2 ? undefined : true}>
```

2022-05-05 11:50 UTC, oyvind-stenhaug commented on web/components/TextBlock/Sponsorships/Sponsorships.tsx
> +                  name={b || ''}
Looks OK to me, the renaming of `b` is also good

2022-05-05 11:54 UTC, oyvind-stenhaug commented on web/components/VenueNav/VenueNav.tsx
> +      [mainVenue?.name || '']: 'Main venue',
OK. Switch is not capable of skipping the main venue comparison if there is no main venue, but as mentioned that's a corner case anyway.

2022-05-05 12:39 UTC, j0nas commented on web/util/pages.ts
> +    ? slug.reduce((acc, curr) => urlJoin(acc, curr, { trailingSlash: false }))
Mea culpa, good catch.

2022-05-05 12:39 UTC, j0nas commented on web/util/pages.ts
> +import { ParsedUrlQuery } from 'querystring';
bc2de6b

2022-05-05 13:13 UTC, oyvind-stenhaug approved these changes
Thanks, looks good to me!

2022-05-05 13:16 UTC, merged